// <auto-generated />
using entitytesting.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace entitytesting.Migrations
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20180410163650_AddAgeToCharacter")]
    partial class AddAgeToCharacter
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("entitytesting.Models.Character", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("CharacterID");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("entitytesting.Models.CharacterSheet", b =>
                {
                    b.Property<int>("CharacterSheetID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CharacterID");

                    b.Property<int>("Charisma");

                    b.Property<int>("Constitution");

                    b.Property<int>("Dexterity");

                    b.Property<int>("Intelligence");

                    b.Property<int>("Strength");

                    b.Property<int>("Wisdom");

                    b.HasKey("CharacterSheetID");

                    b.HasIndex("CharacterID");

                    b.ToTable("CharacterSheets");
                });

            modelBuilder.Entity("entitytesting.Models.CharacterSheet", b =>
                {
                    b.HasOne("entitytesting.Models.Character")
                        .WithMany("CharacterSheet")
                        .HasForeignKey("CharacterID");
                });
#pragma warning restore 612, 618
        }
    }
}
